name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r complex.zip src
      - uses: actions/upload-artifact@v2
        with:
          path: complex.zip
